trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16.x'  # Update to a more recent Node.js version if needed
  displayName: 'Install Node.js'

- script: |
    node -v
    npm -v
  displayName: 'Check Node.js and npm versions'

- script: |
    npm ci  # Use npm ci for clean install, especially in CI environments
    npm run build
  displayName: 'npm install and build'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'dist'  # Adjust this path based on your build output directory
    ArtifactName: 'drop'
    publishLocation: 'Container'
  displayName: 'Publish Build Artifacts'
